### ISSUE TITLE
My DNS resolution issue in Xenial (relevant links)

### ISSUE THREAD

**Issue by cinnamoner** [cinnamoner/Just-for-learning-a-bit-of-css-and-js#2]
http://askubuntu.com/questions/622470/dns-probe-finished-bad-config-error-in-ubuntu-14-04/622493#622493
http://unix.stackexchange.com/questions/280264/no-dns-resolution-after-upgrade-from-ubuntu-14-04-to-16-04

**Comment by cinnamoner** [comment]
@MichaelTunnell What do you think? ^

**Comment by cinnamoner** [comment]
@Lestcape Never had/don't have this DNS resolution issue with distros based on Trusty.
However, I have the issue with distros based on Xenial (Mint, Peppermint, Neon, you name it).
***
I've applied one of the fixes described in the 2nd link, right above, and the issue is more ore less solved.
***
What's your opinion? When I say *more or less* it means things still don't go as smoothly as on Trusty.

**Comment by lestcape** [comment]
@cinnamoner as it's it's Mint related, i think, you can open a thread in Mint Foro or speak with clement directly in the irc. I think this is not something that could be fixed easy for your current installation, but maybe could be prevent for next Mint releases. In any case this sound to me as a driver issue and not  related with the distro.

But i'm don't known, i only try to help, but that never occurs to me.

**Comment by cinnamoner** [comment]
It's Debian 8 (Jessie) and Ubuntu 16.04 (Xenial) related. Probably. Mint 18 is obviously affected because it's part of the ecosystem. I'll do more research on it. Thank you. 
***
Oh, I'll have to use the terminal and try every fix one by one again ... there are many ... not just the above.

**Comment by cinnamoner** [comment]
Issue solved. Wasn't a driver issue. Not one sudo magic worked. Was a routing issue. Anyways, I'm glad it's solved.
